version: '3.8'

services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    volumes:
      - ./docker.env:/var/www/html/.env
    networks:
      - shared-services-network

  aggregator:
    build:
      context: .
      dockerfile: Dockerfile.aggregator
    volumes:
      - ./docker.env:/var/www/html/.env
    networks:
      - shared-services-network

networks:
  shared-services-network:
    external: true
